# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeedtem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilefeedtem',
            new_name='ProfileFeedItem',
        ),
    ]
